### ISSUE TITLE
Fail on send telemetry on "warm start" and "shutdown" after timeout

### ISSUE THREAD

**Issue by Vladikamira** [DataDog/datadog-lambda-extension#195]
_**The context:**_
datadog-lambda-extension version `44`
Lambda and DD site is located in the EU.

_**the problem:**_
It looks like dd-extension starts telemetry flush and does not stop before each invocation ends when Lambda enters the IDLE state. We see that by `Warnings` and `Errors` messages when the function gets invoked either after the `warm start` on subsequent invocation or the `shutdown` event.
    Error/Warning pops up when more than [WaitTimeout (5 seconds)](https://github.com/DataDog/datadog-agent/blob/main/pkg/serverless/daemon/daemon.go#L34) has passed after the previous invocation (I didn't dive deep into the code, but that looks like the proper threshold).

Example of the `WARN`:
```
DD_EXTENSION | WARN | Could not send payload: Post "https://http-intake.logs.datadoghq.eu/api/v2/logs": context deadline exceeded (Client. Timeout exceeded while awaiting headers)
```

example of the `ERROR`:
```
 | UTC | DD_EXTENSION | ERROR | Exporting failed. No more retries left. Dropping data.
``` 

Here are some examples in screenshots:

WARN on subsequent invocation:

![WARN on Invocation](https://github.com/DataDog/datadog-lambda-extension/assets/5423271/dddd6690-78fd-4f7b-824d-b1d7b452b11e)

![WARN (with debug) on invocation](https://github.com/DataDog/datadog-lambda-extension/assets/5423271/5cf9de4e-94d8-4eb5-8f94-a6b0c6fa00a2)

WARN on shutdown event:
![WARN on shutdown](https://github.com/DataDog/datadog-lambda-extension/assets/5423271/ba1009cf-9b35-49b2-8a37-a1280f2d13f1)

![WARN on shutdown with debug](https://github.com/DataDog/datadog-lambda-extension/assets/5423271/17ba66f7-3c89-4c19-8483-2f8f731bb40a)

ERROR on shutdown (this one seems to be from the OTLP part of the agent):

![ERROR and shutdown event](https://github.com/DataDog/datadog-lambda-extension/assets/5423271/5f21a7d9-5158-4d25-afa3-f6c21d58def2)

**Comment by Vladikamira** [comment]
problem reproduced on the datadog-lambda-extension version `53` (cannot check `55` as the image is not published)

**Comment by Vladikamira** [comment]
> Hi @Vladikamira i'm able to find v55's tag here https://hub.docker.com/r/datadog/lambda-extension/tags. May you clarify if we are on the same page about
> 
> > cannot check 55 as the image is not published
indeed, I will try that one from DockerHub, thanks! 👍 
We are using the AWS one: https://gallery.ecr.aws/datadog/lambda-extension, the last one there is `53`

**Comment by Vladikamira** [comment]
version `55` has the same problem

![Screenshot 2024-02-23 at 10 41 06](https://github.com/DataDog/datadog-lambda-extension/assets/5423271/5de97375-2372-4da9-ac4f-03006139f7ed)

**Comment by hghotra** [comment]
Hi @Vladikamira, can you try the latest version of the extension and report back? This was fixed in a recent version of the extension.

**Comment by DylanLovesCoffee** [comment]
Upgrading to v59+ should include a [change](https://github.com/DataDog/datadog-agent/commit/7e6dc75557baf749eda9348d9d24b15ea40301f6) that improves the flushing logic for sending logs. Could we give that a try and then keep us updated?

**Comment by Vladikamira** [comment]
anyway, this issue is fixed, therefore I'm closing PR, thanks! 🙏 
I'Il open another one for a new issue 😄

**Comment by Vladikamira** [comment]
sorry, we do not have these massages anymore after the upgrade to v64
```
DD_EXTENSION | WARN | Could not send payload: Post "https://http-intake.logs.datadoghq.eu/api/v2/logs": EOF (Client.Timeout exceeded while awaiting headers)
```
but we still have these
```
 DD_EXTENSION | WARN | SyncForwarder.sendHTTPTransactions failed to send: error while sending transaction, rescheduling it: Post "https://7-55-3-app.agent.datadoghq.eu/api/v1/series": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
![Screenshot 2024-09-12 at 14 00 09](https://github.com/user-attachments/assets/2ecb3f91-fe6f-4024-9447-85325a11961b)

**Comment by fatbasstard** [comment]
Hitting the same errors on V65

**Comment by DylanLovesCoffee** [comment]
Hi all - if possible, does an upgrade to our [latest iteration (v68)](https://github.com/DataDog/datadog-lambda-extension?tab=readme-ov-file#next-generation-lambda-extension) of the Lambda Extension fix the issue? The newest Extension changes  how we were previously sending logs and metrics to Datadog and should also be more performant.

**Comment by hghotra** [comment]
Closing this since there's been no activity on this issue - reopen if the issue persists!
